{
 "title": "Grafana-Prometheus-Node_Exporter_Host_Metrics_Dashboard",
 "description": "This is a simple Grafana Dashboard to display Host Metrics such CPU, Memory, DISK IO, Load Average, collected using the Node Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d"
   },
   {
    "name": "node",
    "label": "IPORHOST",
    "query": "label_values(node_exporter_build_info,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Load Avarage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_1m"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_5m"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_15m"
    }
   ]
  },
  {
   "title": "Total CPUs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Statistics",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}_sys"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}_user"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}_iowait"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 7 },
   "targets": [
    {
     "expr": "avg_over_time(node_filesystem_size_bytes{instance=~\"$node\",fstype=~\"ext4\"}[1d])"
    },
    {
     "expr": "avg_over_time(node_filesystem_avail_bytes{instance=~\"$node\",fstype=~\"ext4\"}[1d])"
    },
    {
     "expr": "1-(node_filesystem_avail_bytes{instance=~'$node',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "Memory Statistics",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "avg_over_time(node_memory_MemTotal_bytes {instance=~\"$node\"}[$interval])"
    },
    {
     "expr": "node_memory_MemFree_bytes {instance=~\"$node\"}"
    },
    {
     "expr": "avg_over_time(node_memory_MemAvailable_bytes {instance=~\"$node\"}[$interval])"
    },
    {
     "expr": "avg_over_time(node_memory_Buffers_bytes {instance=~\"$node\"}[$interval])"
    },
    {
     "expr": "avg_over_time(node_memory_Cached_bytes {instance=~\"$node\"} [$interval])"
    },
    {
     "expr": "avg_over_time(node_memory_Active_bytes {instance=~\"$node\"} [$interval])"
    },
    {
     "expr": "avg_over_time(node_memory_SwapCached_bytes {instance=~\"$node\"}[$interval])"
    },
    {
     "expr": "avg_over_time(node_memory_SwapTotal_bytes {instance=~\"$node\"}[$interval])"
    },
    {
     "expr": "avg_over_time(node_memory_SwapFree_bytes {instance=~\"$node\"}[$interval])"
    }
   ]
  },
  {
   "title": "Disk_IO_Read/Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps", "label": "IO_Read/Write" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_IO"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_Read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_Write"
    }
   ]
  }
 ]
}